---
  
- hosts: webservers
  become: true
  
  tasks:

  - name: Updation of Cache
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 7200

  - name: make sure snmp is installed
    apt: name=snmp state=present
  
  - name: make sure snmpd is installed
    apt: name=snmpd state=present

  - name: make sure snmpd is configured
    copy: src=snmpd.conf dest=/etc/snmp/snmpd.conf

  - name: Restarting snmpd
    service:
       name: snmpd
       state: restarted
    become: yes   

  - name: Installing Nginx
    become: true
    apt:
      name: nginx
      state: latest  

  - name: Insert nginx file  
    template:
       src: "./nginx.conf"
       dest: "/etc/nginx/sites-available/default1"
 
  - name: Restarting Nginx
    service:
       name: nginx
       state: restarted
    become: yes   

  - name: Install PHP 
    become: true
    apt:
      name: php
      state: latest       
  
  - name: PHP-FPM Package installation 
    become: true
    apt:
      name: php7.4-fpm
      state: latest   

  - name: Copying file
    become: yes
    copy: 
     src: ./index.php
     dest: /var/www/html/index.php
  
- hosts: haproxy
  become: true

  vars:
    haproxy_maxconns: 4096
    haproxy_backlog: 2
    haproxy_timeout_q: 400ms
    haproxy_timoutconnect: 5000ms
    haproxy_timeoutclient: 5000ms
    haproxy_timoutserver: 5000ms
    haproxy_http_timeout: 15s
    haproxy_balance: leastconn
    haproxy_frontend_port: 80

  tasks:
  
  - name: Update cache
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 7200

  - name: Installing packages
    become: true
    apt:
      name: haproxy
      state: latest   

  - name: Deploy HAProxy  
    template:
      src: ./haproxy.conf
      dest: "/etc/haproxy/haproxy.cfg"

  - name: restart Haproxy
    service:
      name: haproxy
      state: restarted
    
  - name: Installing the packages from Nginx
    become: true
    apt:
      name: nginx
      state: latest  
  
  - name: make sure sites-available should copy the file 
    copy: 
     src: "./nginx2.conf" 
     dest: /etc/nginx/sites-available/default    
  
  - name: copy nginx.conf file 
    template: 
     src: "./nginx1.conf" 
     dest: /etc/nginx/nginx.conf

  - name: restart  nginx
    service:
      name: nginx
      state: restarted 

  - name: make sure snmp is installed
    apt: name=snmp state=latest  
 
- hosts: webservers
  gather_facts: y
  
  tasks:
  
  - name: haproxy redumentary function test-1  
    uri: url=http://localhost/ return_content=yes
    register: html_body
  - debug: msg='{{ html_body.content }}'

- hosts: devhaproxy
  gather_facts: y
  tasks:

  - name: checking snmpwalk -1
    shell: "snmpwalk -t 1 -r 1 -v2c -c public localhost:1161"
    register: "output"
  - debug: var=output.stdout_lines
  
  - name: checking snmpwalk -2 
    shell: "snmpwalk -t 1 -r 1 -v2c -c public localhost:1161"
    register: "output"
  - debug: var=output.stdout_lines
 
  - name: checking snmp walk -3
    shell: "snmpwalk -t 1 -r 1 -v2c -c public localhost:1161"
    register: "output"
  - debug: var=output.stdout_lines
